name: 'Build'
on:
  push: 
    branches: 
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - working-directory: ./test_app
        run: |
          npm ci
          node index.js &
          npm run test
          killall node