on: 
  workflow_dispatch:
jobs:
  run:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/js-invoke-workflow
        with:
          token: ${{ secrets.GITHUB_TOKEN }}