name: 'K8S Test'
on: 
  workflow_run:
    workflows: ["Docker Publish"]
    branches: [master]
    types: [completed]
jobs:
  k8s-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: balchua/microk8s-actions@v0.2.1
        with:
          channel: '1.19/stable'
          addons: '["dns", "rbac", "storage", "traefik"]'
      - name: 'Deploy Test App With Helm'
        working-directory: helm/test-app
        run: |
          helm upgrade --install --wait --timeout 120s test-app .
      - name: 'Setup Node.JS'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: 'Run APP E2E Tests'
        working-directory: ./test_app
        env:
          APP_PORT: 8080
        run: |
          npm ci
          npm test

