name: 'K8S Test'
on: 
  workflow_run:
    workflows: ["Docker Publish"]
    branches: [master]
    types: [completed]
jobs:
  k8s-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: balchua/microk8s-actions@v0.2.1
        with:
          channel: '1.19/stable'
          addons: '["dns", "rbac", "storage", "traefik"]'
      - name: 'Deploy Test App With Helm'
        working-directory: helm/test-app
        run: |
          helm upgrade --install --wait --timeout 120s test-app .