name: 'K8S Test'
on: 
  workflow_run:
    workflows: ["Docker Publish"]
    branches: [master]
    types: [completed]
jobs:
  k8s-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: balchua/microk8s-actions@v0.2.2
        with:
          channel: '1.22/stable'
          addons: '["dns", "rbac", "storage", "traefik"]'
      - name: 'Deploy Test App With Helm'
        working-directory: helm/test-app
        run: |
          export APP_HOST=$(hostname)
          helm upgrade --install --wait --timeout 120s --set ingress.defaultHostName="$APP_HOST" test-app .
      - name: 'Setup Node.JS'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: 'Echo Service Info'
        run: |
          kubectl get nodes -o wide
          kubectl get services --all-namespaces -o wide
          kubectl get ingresses --all-namespaces  -o wide
      - name: 'Run APP E2E Tests'
        working-directory: ./test_app
        env:
          APP_PORT: 80
        run: |
          export APP_HOST=$(hostname)
          npm ci
          npm test

