name: Install MicroK8S
on: 
  workflow_dispatch:
jobs:
  run:
    strategy:
      fail-fast: true
      matrix: 
        run: [0, 1, 2, 3 , 4]
    runs-on: 'ubuntu-latest'
    steps:
      - name: install microk8s
        run: |
          sudo snap install microk8s --classic
        timeout-minutes: 8
      - name: dump logs
        if: always()
        run: |
          sudo journalctl --since yesterday