name: Deploy
on: 
  push: 
    branches: 
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2
      - run: |
          exit 0